### ISSUE TITLE
[Windows][Firefox] Problem with unicode characters in link names (mishandling of encoding)

### ISSUE THREAD

**Issue by e-d-n-a** [FlyingWolFox/Bookmarks-to-Dir#2]
Hey,

thank you for making this code and especially the package ([Netscape-Bookmarks-File-Parser](https://github.com/FlyingWolFox/Netscape-Bookmarks-File-Parser)) publicly available,
it was just what I needed and it works great, for the most part. :)

**Here is Issue-Nr. 2 of the 2, that I got for you:**

I noticed character errors in the file names of the link files created from the bookmark file.
It's caused by not reading in the bookmark file with the proper encoding specified with the "open"-function.
"UTF-8" is the obvious encoding used in the bookmark files as stated with the meta tag:

`<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">`

But Python 3.9 still does not always use "UTF-8" as encoding by default,  when reading/writing via "open".
It still depends on the system settings. You can read all the details about that in [PEP 597](https://www.python.org/dev/peps/pep-0597/)!

So, when you know, you're handling files with "UTF-8" content, you have to explicitly enable that via the "encoding"-argument.

**It is therefore easily fixed, by turning:**

[Line #92 of "bookmark_to_dir.py"](https://github.com/FlyingWolFox/Bookmarks-to-Dir/blob/01670e3a1da5d6b7bf673d2a3471f194ad4c36d0/bookmark_to_dir.py#L92)
into
`with open(file_path, 'r', encoding='utf-8') as file:`

and

[Line #134 of "bookmark_to_dir.py"](https://github.com/FlyingWolFox/Bookmarks-to-Dir/blob/01670e3a1da5d6b7bf673d2a3471f194ad4c36d0/bookmark_to_dir.py#L134)
into
`with open(file_destination, 'w', encoding='utf-8') as bookmarks:`

**Sorry, for not providing a PR!**

**Comment by FlyingWolFox** [comment]
Thanks for the heads up!
